"""Sync allowed_signers from all members of a GitHub organization."""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import requests


def fetch_org_members(org_name: str, token: str) -> list[str]:
    """Fetch login names of all org members."""
    headers = {"Authorization": f"Bearer {token}", "User-Agent": "auths-fleet"}
    members: list[str] = []
    page = 1

    while True:
        resp = requests.get(
            f"https://api.github.com/orgs/{org_name}/members",
            headers=headers,
            params={"per_page": 100, "page": page},
        )
        resp.raise_for_status()
        batch = resp.json()
        if not batch:
            break
        members.extend(m["login"] for m in batch)
        page += 1

    return members


def fetch_ed25519_keys(username: str) -> list[str]:
    """Fetch Ed25519 SSH public keys for a GitHub user."""
    resp = requests.get(
        f"https://github.com/{username}.keys",
        headers={"User-Agent": "auths-fleet"},
    )
    if resp.status_code != 200:
        return []

    keys: list[str] = []
    for line in resp.text.strip().splitlines():
        if line.startswith("ssh-ed25519"):
            keys.append(line.strip())
    return keys


def sync_signers(org_name: str, token: str, output_path: Path) -> None:
    """Sync allowed_signers from GitHub org members."""
    print(f"Fetching members of {org_name}...")
    members = fetch_org_members(org_name, token)
    print(f"Found {len(members)} members.")

    lines = [
        "# Auths allowed signers file",
        f"# Synced from GitHub org: {org_name}",
        f"# Generated by fleet/sync_from_github_org.py",
        "",
    ]

    added = 0
    for username in sorted(members):
        keys = fetch_ed25519_keys(username)
        for key in keys:
            lines.append(f"{username}@github.com {key}")
            added += 1
        if not keys:
            print(f"  Warning: {username} has no Ed25519 keys")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n")
    print(f"\nSynced {added} keys for {len(members)} members to {output_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Sync allowed_signers from GitHub org")
    parser.add_argument("--org", required=True, help="GitHub organization name")
    parser.add_argument("--token", default=os.environ.get("GITHUB_TOKEN"), help="GitHub token (or set GITHUB_TOKEN)")
    parser.add_argument("--output", default=".auths/allowed_signers", help="Output path for allowed_signers")
    args = parser.parse_args()

    if not args.token:
        print("Error: GitHub token required. Set GITHUB_TOKEN or use --token.", file=sys.stderr)
        sys.exit(1)

    sync_signers(args.org, args.token, Path(args.output))


if __name__ == "__main__":
    main()
